## Metadata
title: Daryl Fritz
description: A Toronto web developer who enjoys travel, beer, and technology.
url: http://darylfritz.com
picture: /images/darylfritz.png

## Site Configuration
analytics: UA-371632-3
google-profile: 103291878983108857970

## Jekyll Configuration
source:      .
destination: ./_site
plugins:     ./_plugins
permalink:  /:year/:month/:day/:title.html

exclude:
- README.md
- LICENSE
- Rakefile
- Gemfile
- Gemfile.lock
